// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbnoSsj0xHE6ywgqwjsO5ss_aGSt5NwBA',
    appId: '1:360638242456:web:47a41e8c04a65ab741faed',
    messagingSenderId: '360638242456',
    projectId: 'project-01-696cf',
    authDomain: 'project-01-696cf.firebaseapp.com',
    storageBucket: 'project-01-696cf.firebasestorage.app',
    measurementId: 'G-6B2Y4G6VY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz8WvR-0t4pDul7zVkmm8Dv0wzDV9DIE0',
    appId: '1:360638242456:android:2bc843592075bab741faed',
    messagingSenderId: '360638242456',
    projectId: 'project-01-696cf',
    storageBucket: 'project-01-696cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn2Z7S7eTsB01Z9og3wLYFdExntZL-Sgc',
    appId: '1:360638242456:ios:08714f0007c89b4e41faed',
    messagingSenderId: '360638242456',
    projectId: 'project-01-696cf',
    storageBucket: 'project-01-696cf.firebasestorage.app',
    iosBundleId: 'com.example.project01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn2Z7S7eTsB01Z9og3wLYFdExntZL-Sgc',
    appId: '1:360638242456:ios:08714f0007c89b4e41faed',
    messagingSenderId: '360638242456',
    projectId: 'project-01-696cf',
    storageBucket: 'project-01-696cf.firebasestorage.app',
    iosBundleId: 'com.example.project01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbnoSsj0xHE6ywgqwjsO5ss_aGSt5NwBA',
    appId: '1:360638242456:web:6af4324b7c4409d941faed',
    messagingSenderId: '360638242456',
    projectId: 'project-01-696cf',
    authDomain: 'project-01-696cf.firebaseapp.com',
    storageBucket: 'project-01-696cf.firebasestorage.app',
    measurementId: 'G-Z64LHDDXG6',
  );
}
